export enum UnitPath {
  RedJet1 = 'red/a1',
  RedJet2 = 'red/a2',
  RedHeli1 = 'red/a3',
  RedHeli2 = 'red/a4',
  RedTank1 = 'red/a5',
  RedTank2 = 'red/a6',
  RedAA = 'red/a7',
  RedTank3 = 'red/a8',
  RedInf1 = 'red/a9',
  RedInf2 = 'red/a10',
  PurpleJet1 = 'purple/a1',
  PurpleJet2 = 'purple/a2',
  PurpleHeli1 = 'purple/a3',
  PurpleHeli2 = 'purple/a4',
  PurpleTank1 = 'purple/a5',
  PurpleTank2 = 'purple/a6',
  PurpleAA = 'purple/a7',
  PurpleTank3 = 'purple/a8',
  PurpleInf1 = 'purple/a9',
  PurpleInf2 = 'purple/a10',
  RedWarCat = 'red/warcat',
  PurpleWarCat = 'purple/warcat',
}
